# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
#
pod 'TesseractOCRiOS', '3.4.0'
pod 'GPUImage', '0.1.6'

target 'cameraTest' do

end

target 'cameraTestTests' do

end

